export const sudokuCellTemplateTest = [
    [
      {
        cellId: "00",
        value: "23",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "01",
        value: "23",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "02",
        value: "23",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "03",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "04",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "05",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "06",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "07",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "08",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
    ],
  
    [
      {
        cellId: "10",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "11",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "12",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "13",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "14",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "15",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "16",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "17",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "18",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
    ],
  
    [
      {
        cellId: "20",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "21",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "22",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "23",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "24",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "25",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "26",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "27",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "28",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
    ],
  
    [
      {
        cellId: "30",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "31",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "32",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "33",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "34",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "35",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "36",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "37",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "38",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
    ],
  
    [
      {
        cellId: "40",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "41",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "42",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "43",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "44",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "45",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "46",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "47",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "48",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
    ],
  
    [
      {
        cellId: "50",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "51",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "52",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "53",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "54",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "55",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "56",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "57",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "58",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
    ],
  
    [
      {
        cellId: "60",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "61",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "62",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "63",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "64",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "65",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "66",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "67",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "68",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
    ],
  
    [
      {
        cellId: "70",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "71",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "72",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "73",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "74",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "75",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "76",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "77",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "78",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
    ],
  
    [
      {
        cellId: "80",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "81",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "82",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "83",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "84",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "85",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-dark",
      },
      {
        cellId: "86",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "87",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
      {
        cellId: "88",
        value: "",
        cellReadOnly: true,
        color: "",
        fontWeight: "bolder",
        cellClassName: "btn btn-outline-info",
      },
    ],
  ];